# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt ./
COPY streamlit_app.py ./

# Install any needed packages specified in requirements.txt
RUN Pip install --upgrade pip
RUN pip install -r requirements.txt


# Copy the rest of the application code into the container at /app
#COPY . .

# Expose the port that Streamlit listens on
EXPOSE 8501

# Run Streamlit when the container launches
ENTRYPOINT ["streamlit", "run", "streamlit_app.py","server.port=8501","server.address=0.0.0.0"]
