# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt and other necessary files
COPY requirements.txt /app
COPY streamlit_app.py /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your Streamlit app runs on
EXPOSE 8501

# Command to run your Streamlit app
CMD ["streamlit", "run", "--server.port", "8501", "streamlit_app.py"]
